### ISSUE TITLE
steps' working-directory is ignored?

### ISSUE THREAD

**Issue by nwf-msr** [ChristopherHX/github-act-runner#61]
I have a workflow yaml file that separates `cmake` and `ninja` something like this:
```
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        pwd
        NINJA_STATUS="%p [%f:%s/%t] %o/s, %es" ninja
```

This works fine on the GitHub hosted runners, but when I try using `github-act-runner`, that `pwd` prints out (for example) `/tmp/.cache/act/95a278de-91a6-4964-bd11-4100ef2b7fd9/hostexecutor` rather than the `/tmp/.cache/act/95a278de-91a6-4964-bd11-4100ef2b7fd9/hostexecutor/build` I expect.

I'm not sure if this is related to https://github.com/nektos/act/commit/bea32d5651c94049173799c496bdc87a4b304f02 which looks to have landed in https://github.com/nektos/act/releases/tag/v0.2.25 or if it's something else entirely.

**Comment by ChristopherHX** [comment]
Thank you for testing this runner.

This should not be ignored, but you found a bug in my act fork.
I guess that the docker executor doesn't have this bug. Regression caused by merging act 9 month ago: https://github.com/ChristopherHX/act/blob/3c3f6606ced23bb378de3ff5e26ba183e9368705/pkg/container/host_executor.go#L330, have to swap the user and workdir parameter.

It is possible that some 0.0.x releases are not affected.
